paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos
      tags:
        - Productos
      responses:
        "200":
          description: Todos los productos se obtuvieron correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
        "500":
          description: Error interno del servidor
    post:
      summary: Crea un nuevo producto
      tags:
        - Productos
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
  /api/products/manageProducts/:
    get:
      summary: Obtiene todos los productos
      tags:
        - Productos
      responses:
        "200":
          description: Todos los productos se obtuvieron correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
        "500":
          description: Error interno del servidor
  /api/products/{pid}:
    get:
      summary: Obtiene un producto por su id
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          description: Id del producto
          required: true
          schema:
            type: string
      responses:
        "200":
          description: El producto se obtuvo correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: El producto no existe
        "500":
          description: Error interno del servidor
  /api/products/update/{pid}:
    put:
      summary: Actualiza un producto por su id
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          description: Id del producto
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: El producto se actualizó correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: El producto no existe
        "500":
          description: Error interno del servidor
  /api/products/delete/{pid}:
    delete:
      summary: Elimina un producto por su id
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          description: Id del producto
          required: true
          schema:
            type: string
      responses:
        "200":
          description: El producto se eliminó correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: El producto no existe
        "500":
          description: Error interno del servidor
components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number
        stock:
          type: number
        image:
          type: string
        category:
          type: string
        brand:
          type: string
        rating:
          type: number
        numReviews:
          type: number
        countInStock:
          type: number
        reviews:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              rating:
                type: number
              comment:
                type: string
    Products:
      type: array
      items:
        $ref: "#/components/schemas/Product"
